version: 0.0
os: linux
files:
  - source: .
    destination: /flask-cd-pipeline-with-aws-codedeploy/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu